### ISSUE TITLE
403 -Forbidden; Logged-in use not supported 

### ISSUE THREAD

**Issue by anuraagpunjabi** [FreekBes/insta_reddit_bot#14]
Suddenly today (22/05/2021) i am getting this error...was Instagram API updated today? It was working fine before today 

```
Initializing...
PostsStatus initialized
Current time: 11:47
Parsing cookies...
Signing in to Instagram...
Could not sign in to Instagram
IgResponseError: POST /api/v1/accounts/get_prefill_candidates/ - 403 Forbidden; Logged-in use not supported
    at Request.handleResponseError (C:\Users\HP\Documents\GitHub\insta_reddit_bot\node_modules\instagram-private-api\dist\core\request.js:125:16)
    at Request.send (C:\Users\HP\Documents\GitHub\insta_reddit_bot\node_modules\instagram-private-api\dist\core\request.js:53:28)
    at async AccountRepository.getPrefillCandidates (C:\Users\HP\Documents\GitHub\insta_reddit_bot\node_modules\instagram-private-api\dist\repositories\account.repository.js:273:26)
```

**Comment by anuraagpunjabi** [comment]
Deleted cookies and it works perfectly

**Comment by FreekBes** [comment]
May I ask how your removed the cookies? I deleted cookies.json, but it still isn't working.

**Comment by anuraagpunjabi** [comment]
Yes i deleted cookies.json but i need to delete it everytime before I run the bot
