### ISSUE TITLE
Hmm running on Mac OS

### ISSUE THREAD

**Issue by couldbejake** [FreekBes/insta_reddit_bot#23]
jakenelson@Jakes-MacBook-Pro-2 insta_reddit_bot-master % node bot.js 
Initializing...
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'instagram-private-api'
Require stack:
- /Users/jakenelson/Desktop/insta_reddit_bot-master/handlers/instagram.js
- /Users/jakenelson/Desktop/insta_reddit_bot-master/bot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/jakenelson/Desktop/insta_reddit_bot-master/handlers/instagram.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jakenelson/Desktop/insta_reddit_bot-master/handlers/instagram.js',
    '/Users/jakenelson/Desktop/insta_reddit_bot-master/bot.js'
  ]
}
jakenelson@Jakes-MacBook-Pro-2 insta_reddit_bot-master %

**Comment by couldbejake** [comment]
Sorry stupid mistake, thank you man
