### ISSUE TITLE
Getting Response Error 302 - Won't login to instagram

### ISSUE THREAD

**Issue by Smajkan** [FreekBes/insta_reddit_bot#25]
Hello, I am getting this error:
```
~/AzureFavorableStructures$ node bot.js
Initializing...
Temporary folder does not exist! Creating...
Temporary folder created.
posts.json missing! Creating...
posts.json cleared
PostsStatus initialized
Current time: 20:58
Signing in to Instagram...
Could not sign in to Instagram
IgResponseError: POST /api/v1/accounts/msisdn_header_bootstrap/ - 302 Found; 
    at Request.handleResponseError (/home/runner/AzureFavorableStructures/node_modules/instagram-private-api/dist/core/request.js:125:16)
    at Request.send (/home/runner/AzureFavorableStructures/node_modules/instagram-private-api/dist/core/request.js:53:28)
    at async AccountRepository.msisdnHeaderBootstrap (/home/runner/AzureFavorableStructures/node_modules/instagram-private-api/dist/repositories/account.repository.js:251:26)
Logged in to Discord as **************
```

Does anyone know how to fix this?

**Comment by FreekBes** [comment]
Check the Instagram app or website, there's possibly a popup button you are required to click on due to a removed post or suspicious activity. Let me know if that's not the case!

**Comment by Smajkan** [comment]
Doesn't seem like that's an error. I was able to login successfully through the phone and the browser on instagram without any popup buttons or removed posts (this is first time I am running this bot btw.)

**Comment by Smajkan** [comment]
A little update on this is that it's running perfectly fine on Windows. 
Seems like it does have some problems with VPS?

**Comment by FreekBes** [comment]
Are you running it on the same network you normally log in from?

**Comment by Smajkan** [comment]
No, I don't and I assume that is reason why am I getting this error.
Is there any way of fixing this?

**Comment by FreekBes** [comment]
Try stopping the bot, deleting the cookies.json file in the handlers folder, then change the seed in the settings.json file and restart the bot. This might fix your issue.

**Comment by Smajkan** [comment]
That was the first thing that I've done actually 
@FreekBes

**Comment by FreekBes** [comment]
Issue is described [here](https://github.com/dilame/instagram-private-api/issues/1417). Seems to be a dependency issue. I suggest waiting a while before trying again (after clearing cookies as well), maybe that helps.
